USE familycare_db;

ALTER TABLE caregivers
  ADD COLUMN IF NOT EXISTS rating       DECIMAL(2,1) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS total_reviews INT          DEFAULT 0,
  ADD COLUMN IF NOT EXISTS location      VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS languages     VARCHAR(200) DEFAULT NULL;
